# Generated by Django 4.2.16 on 2025-02-08 09:45

from django.db import migrations


def enable_rls_for_all(apps, schema_editor):
    with schema_editor.connection.cursor() as cursor:
        # Enable RLS on all tables in the public schema
        cursor.execute("""
            DO $$ 
            DECLARE
                r RECORD;
            BEGIN
                -- Loop through all tables in the public schema
                FOR r IN 
                    SELECT table_name 
                    FROM information_schema.tables 
                    WHERE table_schema = 'public'
                LOOP
                    -- Enable RLS for each table
                    EXECUTE 'ALTER TABLE public.' || r.table_name || ' ENABLE ROW LEVEL SECURITY';
                END LOOP;
            END $$;
        """)

        # Create a default policy for all tables
        cursor.execute("""
            DO $$ 
            DECLARE
                r RECORD;
            BEGIN
                -- Loop through all tables in the public schema
                FOR r IN 
                    SELECT table_name 
                    FROM information_schema.tables 
                    WHERE table_schema = 'public'
                LOOP
                    -- Create a default policy for each table
                    EXECUTE 'CREATE POLICY select_policy ON public.' || r.table_name || ' FOR SELECT USING (true)';
                END LOOP;
            END $$;
        """)

class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0003_rename_totalincents_order_total_in_cents_and_more'),
    ]

    operations = [
                migrations.RunPython(enable_rls_for_all),
    ]
